export const AUTH_STATUS = 'AUTH_STATUS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const CREATE_STREAM = 'CREATE_STREAM';
export const UPDATE_STREAM = 'UPDATE_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
